import type { Metadata } from "next";
import "../globals.css";
import { Footer, Header, Logo, NavBar, SideBar } from "@/components/Shared";
import { LayoutManager } from "@/components/Layouts";
import { LoadContext } from "@/components/Containers";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { SpaceToast } from "@/components/Atons";

export const metadata: Metadata = { title: "Divulga Potiguar", description: "Generated by create next app" };

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const session = await getServerSession();
    const user = session?.user;
    if (!session) { redirect("/"); };

    return (
        <html lang="pt-br">
            <body className={"w-full min-h-[100vh] bg-white"}>
                <Header bg={"white"}>
                    <Logo />
                    <NavBar />
                </Header>
                <SpaceToast />
                <LayoutManager>
                    <SideBar username={user?.name ?? "guest"} img={user?.image ?? "avatar.svg"} />
                    <LoadContext>
                        {children}
                    </LoadContext>
                </LayoutManager>
                <Footer />
            </body>
        </html>
    );
}
