import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/components/Header";
import { Logo } from "@/components/Atons";
import { NavBar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Divulga Potiguar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`w-full h-full bg-white`}>
        <Header bg={"white"}>
          <Logo />
          <NavBar />
        </Header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
