import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Divulga Potiguar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-br">
      <body className={"w-full min-h-[100vh] bg-white"}>
        {children}
      </body>
    </html>
  );
}
